### ISSUE TITLE
Documentation: Webapp Container Instructions don't run by default

### ISSUE THREAD

**Issue by mochsner** [ReceiptManager/receipt-manager-webapp#52]
Noticed the documentation for the docker version of the web app was missing some clarity on paths and such. I'm far from as well versed in Docker as I'd hope, so this isn't something I can figure out quite yet, but I wanted to go ahead and create the issue - if I figure out how to run it down the road in Docker, I'll definitely update.

 Snippet from https://receipt-manager-webapp.readthedocs.io/en/latest/installation.html that's running into issues below:

"""" 

Finally, you can start the receipt-parser-webapp.

```
docker run -d –network host –name “receipt-manager-webapp” -v /your/path/onDockerHost/ssl:/app/webroot/ssl -v /your/path/onDockerHost/config:/app/config -e backendIP=”backendIP” -e backendPort=”5558” -e useSSL=”false” dielee/receipt-manager-webapp:latest
```
"""

Even updating the paths, I'm getting 
```
docker: invalid reference format.
See 'docker run --help'.
```

**Comment by monolidth** [comment]
Yes, you are right, will fix it today. Thanks for reporting
